import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/');
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('button', { name: 'Proveedor' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByPlaceholder('Ingrese su email').click();
  await page.getByPlaceholder('Ingrese su email').fill('miimail');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByPlaceholder('Ingrese su email').click();
  await page.getByPlaceholder('Ingrese su email').press('Control+Shift+ArrowLeft');
  await page.getByPlaceholder('Ingrese su email').fill('test2prove@gmail.com');
  await page.getByPlaceholder('Ingrese su contraseña').click();
  await page.getByPlaceholder('Ingrese su contraseña').click();
  await page.getByPlaceholder('Ingrese su contraseña').fill('aaaaa');
  await page.getByPlaceholder('Ingrese su contraseña').click();
  await page.getByPlaceholder('Ingrese su contraseña').fill('aaaaaa');
  await page.getByPlaceholder('Ingrese nuevamente su').click();
  await page.getByPlaceholder('Ingrese nuevamente su').fill('aaaaaa');
  await page.getByText('Correo electrónicoContraseñ').click();
  await page.getByPlaceholder('Ingrese su contraseña').press('Control+Shift+ArrowLeft');
  await page.getByPlaceholder('Ingrese su contraseña').fill('test12');
  await page.getByText('Anterior Continuar').click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByPlaceholder('Ingrese su nombre').click();
  await page.getByPlaceholder('Ingrese su nombre').fill('name');
  await page.getByPlaceholder('Ingrese su apellido').click();
  await page.getByPlaceholder('Ingrese su apellido').fill('name');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('combobox').selectOption('CC');
  await page.getByPlaceholder('Ingrese su número de').click();
  await page.getByPlaceholder('Ingrese su número de').fill('12345');
  await page.getByPlaceholder('Ingrese su número de').click();
  await page.getByPlaceholder('Ingrese su número de').fill('123456');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Registrar' }).click();
  await page.locator('div').filter({ hasText: 'País de residenciaSelecciona' }).nth(1).click();
  await page.getByRole('button', { name: 'Registrar' }).click();
  await page.getByRole('button', { name: 'Registrar' }).click();
  const errorSpan = await page.waitForSelector('.error');
  const errorText = await errorSpan.textContent();
  expect(errorText).toContain('Este campo es requerido');
});