import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/');
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('button', { name: 'Deportista' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByPlaceholder('Ingrese su email').click();
  await page.getByPlaceholder('Ingrese su email').fill('s2115@gmail.com');
  await page.getByPlaceholder('Ingrese su email').press('Tab');
  await page.getByPlaceholder('Ingrese su contraseña').fill('test12');
  await page.getByPlaceholder('Ingrese su contraseña').press('Tab');
  await page.getByPlaceholder('Ingrese nuevamente su').fill('test12');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByPlaceholder('Ingrese su nombre').click();
  await page.getByPlaceholder('Ingrese su nombre').fill('test');
  await page.getByPlaceholder('Ingrese su apellido').click();
  await page.getByPlaceholder('Ingrese su apellido').fill('test');
  await page.getByRole('combobox').selectOption('CC');
  await page.getByPlaceholder('Ingrese su número de').click();
  await page.getByPlaceholder('Ingrese su número de').fill('00032343225');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.locator('select[name="birth_country_id"]').selectOption('1');
  await page.getByText('Ciudad de nacimiento').click();
  await page.locator('select[name="birth_city_id"]').selectOption('1');
  await page.getByText('País de residencia').click();
  await page.locator('select[name="residence_country_id"]').selectOption('10');
  await page.locator('select[name="residence_city_id"]').selectOption('10');
  await page.getByRole('button', { name: 'Registrar' }).click();
  await page.getByPlaceholder('Ingrese su email').click();
  await page.getByPlaceholder('Ingrese su email').fill('s2115@gmail.com');
  await page.getByPlaceholder('Ingrese su email').press('Tab');
  await page.getByPlaceholder('Ingrese su contraseña').fill('test12');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  setTimeout(() => {  }, 1000);
  const toaster = await page.waitForSelector('.toast-message');
  const toasterText = await toaster.textContent();
  expect(toasterText).toContain('éxitosamente');
});