import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/');
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('button', { name: 'Proveedor' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByPlaceholder('Ingrese su email').click();
  await page.getByPlaceholder('Ingrese su email').fill('testtercero115@gmail.com');
  await page.getByPlaceholder('Ingrese su email').press('Tab');
  await page.getByPlaceholder('Ingrese su contraseña').fill('test12');
  await page.getByPlaceholder('Ingrese su contraseña').press('Tab');
  await page.getByPlaceholder('Ingrese nuevamente su').fill('test12');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByPlaceholder('Ingrese su nombre').click();
  await page.getByPlaceholder('Ingrese su nombre').fill('Tercero');
  await page.getByPlaceholder('Ingrese su apellido').click();
  await page.getByPlaceholder('Ingrese su apellido').fill('Tercero');
  await page.getByRole('combobox').selectOption('CC');
  await page.getByPlaceholder('Ingrese su número de').click();
  await page.getByPlaceholder('Ingrese su número de').fill('0212345612135');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByText('Anterior Registrar').click();
  await page.getByRole('button', { name: 'Registrar' }).click();
  await page.locator('select[name="residence_country_id"]').selectOption('1');
  await page.locator('select[name="residence_city_id"]').selectOption('1');
  await page.getByRole('button', { name: 'Registrar' }).click();
  setTimeout(() => {  }, 1000);
  let toaster = await page.waitForSelector('.toast-message');
  let toasterText = await toaster.textContent();
  expect(toasterText).toContain('Usuario guardado éxitosamente');
  await expect(page.getByRole('button', { name: 'Iniciar sesión' })).toBeVisible();

  await page.getByPlaceholder('Ingrese su email').click();
  await page.getByPlaceholder('Ingrese su email').fill('testtercero115@gmail.com');
  await page.getByPlaceholder('Ingrese su email').press('Tab');
  await page.getByPlaceholder('Ingrese su contraseña').fill('test12');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Agregar servicio' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Transporte' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByPlaceholder('Escribe aquí').click();
  await page.getByPlaceholder('Escribe aquí').fill('12');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Registrar' }).click();
  await page.getByPlaceholder('Escribe aquí').click();
  await page.getByPlaceholder('Escribe aquí').fill('test');
  await page.getByRole('button', { name: 'Registrar' }).click();
  setTimeout(() => {  }, 1000);
  toaster = await page.waitForSelector('.toast-message');
  toasterText = await toaster.textContent();
  expect(toasterText).toContain('éxitoso');
});